"""update_salary_to_string

Revision ID: 7b9aa0e8edb3
Revises: b4e8f0924b5b
Create Date: 2026-03-14 17:46:15.349236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9aa0e8edb3'
down_revision: Union[str, Sequence[str], None] = 'b4e8f0924b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents_test')
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('WISHLIST', 'APPLIED', 'INTERVIEW', 'TECHNICAL_TEST', 'REJECTED', 'OFFER', name='applicationstatus'),
               type_=sa.Enum('WISHLIST', 'APPLIED', 'FOLLOW_UP', 'INTERVIEW', 'TECHNICAL_TEST', 'REJECTED', 'OFFER', name='applicationstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('applications', 'salary_proposed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('applications', 'type',
               existing_type=postgresql.ENUM('ALTERNANCE', 'STAGE', name='applicationtype'),
               type_=sa.Enum('ALTERNANCE', 'STAGE', name='applicationtype', native_enum=False),
               existing_nullable=True)
    op.alter_column('documents', 'type',
               existing_type=postgresql.ENUM('CV', 'LM', 'OTHER', name='documenttype'),
               type_=sa.Enum('CV', 'LM', 'OTHER', name='documenttype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'type',
               existing_type=sa.Enum('CV', 'LM', 'OTHER', name='documenttype', native_enum=False),
               type_=postgresql.ENUM('CV', 'LM', 'OTHER', name='documenttype'),
               existing_nullable=False)
    op.alter_column('applications', 'type',
               existing_type=sa.Enum('ALTERNANCE', 'STAGE', name='applicationtype', native_enum=False),
               type_=postgresql.ENUM('ALTERNANCE', 'STAGE', name='applicationtype'),
               existing_nullable=True)
    op.alter_column('applications', 'salary_proposed',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('WISHLIST', 'APPLIED', 'FOLLOW_UP', 'INTERVIEW', 'TECHNICAL_TEST', 'REJECTED', 'OFFER', name='applicationstatus', native_enum=False),
               type_=postgresql.ENUM('WISHLIST', 'APPLIED', 'INTERVIEW', 'TECHNICAL_TEST', 'REJECTED', 'OFFER', name='applicationstatus'),
               existing_nullable=True)
    op.create_table('documents_test',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('version_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_test_pkey'))
    )
    # ### end Alembic commands ###
